name: Test comments

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Find beagle report comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ github.event.pull_request.user.login }}
          body-includes: "<!-- beagle-report -->"
          direction: last

      - name: Read report contents
        id: report_contents
        run: |
          FILE_PATH="comment-body.md"
          if [ -f "$REPORT_PATH" ]; then
            FILE_CONTENT=$(cat "$FILE_PATH")
            echo "file_content<<EOF" >> $GITHUB_OUTPUT
            echo "$FILE_CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "Report file not found: $FILE_PATH"
            echo "report_contents=No report found." >> $GITHUB_OUTPUT
          fi

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            "${{ steps.report_contents.outputs.file_content }}"
            <!-- beagle-report -->
          edit-mode: replace
